on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    name: Compile parse-android-dynparts for the Pinenote
    steps:
      - name: Docker-based compilation
        id: compile-kernel-in-docker
        uses: m-weigand/pinenote_debian_parse-android-dynparts@main
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: parse-android-dynparts
          path: |
            ${{ runner.temp }}/_github_home/parse-android-dynparts_src.tar.gz
            ${{ runner.temp }}/_github_home/parse-android-dynparts
